//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSDictionary, NSString;

@interface TCCDProcess : NSObject {
    BOOL _haveIsPlatformBinary;
    BOOL _isPlatformBinary;
    struct __SecCode *_dynamicCodeRef;
    NSString *_teamIdentifier;
    BOOL _derivedDynamicCode;
    BOOL _derivedTeamIdentifier;
    int _pid;
    unsigned int _auid;
    unsigned int _euid;
    unsigned int _codesignStatus;
    NSString *_responsiblePath;
    NSString *_identifier;
    NSDictionary *_entitlements;
    NSString *_binaryPath;
    NSData *_designatedRequirementData;
    CDStruct_4c969caf _auditToken;
}

+ (id)identifierForInvalidCode;
- (id)arrayValueForEntitlement:(id)arg1;
@property CDStruct_4c969caf auditToken;
@property unsigned int auid;
@property (retain) NSString *binaryPath;
- (BOOL)boolValueForEntitlement:(id)arg1;
@property unsigned int codesignStatus;
- (void)dealloc;
- (id)description;
@property (retain) NSData *designatedRequirementData;
@property (readonly) struct __SecCode *dynamicCodeRef;
@property (retain) NSDictionary *entitlements;
@property unsigned int euid;
- (BOOL)hasEntitlement:(id)arg1
       containsService:(id)arg2
               options:(unsigned long long)arg3;
- (BOOL)hasEntitlement:(id)arg1
    containsServiceAllOrService:(id)arg2
                        options:(unsigned long long)arg3;
@property (retain) NSString *identifier;
- (id)initWithAuditToken:(CDStruct_4c969caf)arg1 responsiblePath:(id)arg2;
- (id)initWithPID:(int)arg1 responsiblePath:(id)arg2;
- (id)logHandle;
@property int pid;
@property (readonly) NSString *responsiblePath;
@property (readonly) NSString *teamIdentifier;

@end
