//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "TCCDPolicyOverrideProtected-Protocol.h"

@class NSDictionary, NSMutableDictionary, NSString;
@protocol OS_dispatch_source;

@interface TCCDPolicyOverride : NSObject <TCCDPolicyOverrideProtected> {
    NSString *plistFilePath;
    NSDictionary *plistDictionary;
    NSMutableDictionary *policyAccessByIdentifier;
    NSObject<OS_dispatch_source> *watchedFileVnodeSource;
}

+ (unsigned long long)evaluateOverridePolicyForAccessByIdentity:(id)arg1
                                                      toService:(id)arg2
                             withIndirectObjectIdentityIdentity:(id)arg3;
+ (void)loadPolicyData;
+ (id)logHandle;
+ (id)orderedOverridePolicies;
+ (id)queue;
+ (id)useString:(id)arg1 orReadFromDefaults:(struct __CFString *)arg2;
- (unsigned long long)_locked_evaluateAccessByIdentity:(id)arg1
                                             toService:(id)arg2
                    withIndirectObjectIdentityIdentity:(id)arg3;
- (id)allowedParser:(id)arg1;
- (id)init;
- (void)loadAndParse;
- (void)loadPlist;
- (struct __CFData *)parseCodeRequirements:(id)arg1;
- (void)parsePlist;
@property (retain) NSDictionary *plistDictionary;
@property (retain) NSString *plistFilePath;
@property (retain) NSMutableDictionary *policyAccessByIdentifier;
@property (retain) NSObject<OS_dispatch_source> *watchedFileVnodeSource;
- (BOOL)validateEntry:(id)arg1
           identifierType:(id)arg2
    codeRequirementString:(id)arg3
              serviceName:(id)arg4
                  allowed:(id)arg5
                  comment:(id)arg6;
- (void)watchPlistChanges;
- (id)watchedPath;

// Remaining properties
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

@end
