//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TCCDIdentity.h"

@class NSData, NSString, TCCDAccessIdentity;

@interface TCCDCodeIdentity : TCCDIdentity {
    NSString *_verifierDescription;
    TCCDAccessIdentity *_resolvedAccessIdentity;
    long long _identifierAuthority;
    long long _displayNamePolicyIdentifier;
    long long _verifierType;
    NSData *_verifierData;
}

+ (id)shortStringForAuthority:(long long)arg1;
@property (readonly) TCCDAccessIdentity *accessIdentity;
- (id)description;
@property long long displayNamePolicyIdentifier;
@property long long identifierAuthority;
- (id)initWithAccessIdentity:(id)arg1;
- (id)initWithIdentifier:(id)arg1
                      authority:(long long)arg2
    displayNamePolicyIdentifier:(long long)arg3
                   verifierType:(long long)arg4
                   verifierData:(id)arg5;
@property (retain) NSData *verifierData;
@property long long verifierType;
@property (readonly) NSString *verifierDescription;

@end
