//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TCCDAccessIndirectObject : NSObject {
    long long _type;
}

+ (id)unusedIndirectObject;
- (id)description;
- (id)initWithType:(long long)arg1;
@property long long type;

@end
