//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden"))) @interface TCCDMessageController
    : NSObject {
    NSMutableDictionary *_messageTypesToHandlers;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)sharedMessageControllerForCurrentPlatform;
- (void)_makeReadyToReceiveMessages;
- (void)_sendMessage:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (id)init;
@property (retain) NSMutableDictionary *messageTypesToHandlers;
@property (retain) NSObject<OS_dispatch_queue> *queue;
- (void)sendMessage:(id)arg1 ofType:(id)arg2 handler:(CDUnknownBlockType)arg3;
- (void)setIncomingMessageType:(id)arg1 handler:(CDUnknownBlockType)arg2;

@end
