//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSNumber, NSSet, NSString;

@interface TCCDService : NSObject {
    BOOL _shouldTreatAsDeprecated;
    BOOL _mdm_isAuthorizationDenyOnly;
    BOOL _mdm_macos_allowedInPayloadDefition;
    BOOL _shouldUseADefaultDescriptionString;
    BOOL _shouldIssueSandboxExtension;
    BOOL _isRevocable;
    BOOL _shouldDisableAlert;
    BOOL _useExternalNotificationOfDenial;
    BOOL _isAccessAllowedByDefault;
    BOOL _isAccessDeniedByDefault;
    BOOL _allowPromptForPlatformBinaries;
    BOOL _shouldAllowUnrestrictedCheckAuditToken;
    BOOL _hasParanoidSecurityPolicy;
    BOOL _hasAdditionalPromptText;
    BOOL _doNotStoreDefaultAllowAccess;
    BOOL _expireOnlyAllowedEntries;
    BOOL _saveExpiredEntries;
    BOOL _applyDevelopmentAuthoriationPolicy;
    BOOL _checkAllowEntitlementOnResponsibleProcess;
    BOOL _macos_pardonMissingUsage;
    BOOL _macos_isPerSystem;
    BOOL _macos_compositionPromoteChildAuthoriationToParent;
    BOOL _macos_hasIndirectObject;
    BOOL _macos_shouldAllowSameTeam;
    NSDictionary *_platformAvailability;
    NSSet *_validOnPlatformNames;
    NSString *_name;
    NSString *_externalName;
    NSString *_usageDescriptionKeyName;
    NSString *_secondaryUsageDescriptionKeyName;
    NSArray *_disallowedOnPlatformSubtypeNameList;
    NSString *_sandboxOperationForDelegation;
    NSArray *_defaultAllowedIdentifiersList;
    NSNumber *_expirySeconds;
    long long _defaultDevelopmentAuthorizationValue;
    NSNumber *_ios_watchKitUserNotificationNumber;
    NSNumber *_iOS_minimumSDKVersionNumber;
    NSNumber *_watchOS_minimumSDKVersionNumber;
    NSNumber *_tvOS_minimumSDKVersionNumber;
    NSNumber *_macos_minimumSDKVersionNumber;
    NSString *_macos_helpAnchor;
    TCCDService *_macos_compositionChildService;
    TCCDService *_macos_compositionParentService;
    NSString *_macos_hardenedRuntimeEntitlementName;
    long long _macos_AXControlComputerAccessType;
}

+ (id)allServices;
+ (id)serviceAll;
+ (id)serviceDescriptionsForPlatformName:(id)arg1;
+ (id)tccdPlatformNameForDYLDPlatformName:(id)arg1;
+ (id)versionStringFromDYLDVersionNumber:(id)arg1;
@property (nonatomic) BOOL allowPromptForPlatformBinaries;
@property (nonatomic) BOOL applyDevelopmentAuthoriationPolicy;
@property (nonatomic) BOOL checkAllowEntitlementOnResponsibleProcess;
- (long long)compare:(id)arg1;
@property (retain, nonatomic) NSArray *defaultAllowedIdentifiersList;
@property (nonatomic) long long defaultDevelopmentAuthorizationValue;
- (id)description;
- (id)descriptionDictionary;
- (long long)developmentAuthorizationValue;
@property (retain, nonatomic) NSArray *disallowedOnPlatformSubtypeNameList;
@property (nonatomic) BOOL doNotStoreDefaultAllowAccess;
@property (nonatomic) BOOL expireOnlyAllowedEntries;
@property (retain, nonatomic) NSNumber *expirySeconds;
@property (retain, nonatomic) NSString *externalName;
@property (nonatomic) BOOL hasAdditionalPromptText;
@property (nonatomic) BOOL hasParanoidSecurityPolicy;
@property (retain, nonatomic) NSNumber *iOS_minimumSDKVersionNumber;
- (id)initWithName:(id)arg1 availability:(id)arg2;
@property (retain) NSNumber *ios_watchKitUserNotificationNumber;
@property (nonatomic) BOOL isAccessAllowedByDefault;
@property (nonatomic) BOOL isAccessDeniedByDefault;
@property (nonatomic) BOOL isRevocable;
@property (nonatomic) long long macos_AXControlComputerAccessType;
@property (nonatomic) __weak TCCDService *macos_compositionChildService;
@property (nonatomic) __weak TCCDService *macos_compositionParentService;
@property (nonatomic) BOOL macos_compositionPromoteChildAuthoriationToParent;
@property (retain, nonatomic) NSString *macos_hardenedRuntimeEntitlementName;
@property (nonatomic) BOOL macos_hasIndirectObject;
@property (retain, nonatomic) NSString *macos_helpAnchor;
@property (nonatomic) BOOL macos_isPerSystem;
@property (retain, nonatomic) NSNumber *macos_minimumSDKVersionNumber;
@property (nonatomic) BOOL macos_pardonMissingUsage;
@property (nonatomic) BOOL macos_shouldAllowSameTeam;
@property (nonatomic) BOOL mdm_isAuthorizationDenyOnly;
@property (nonatomic) BOOL mdm_macos_allowedInPayloadDefition;
@property (retain, nonatomic) NSString *name;
@property (readonly, nonatomic) BOOL pardonMissingUsage;
@property (retain, nonatomic) NSDictionary *platformAvailability;
@property (retain, nonatomic) NSString *sandboxOperationForDelegation;
@property (nonatomic) BOOL saveExpiredEntries;
@property (retain, nonatomic) NSString *secondaryUsageDescriptionKeyName;
@property (nonatomic) BOOL shouldAllowUnrestrictedCheckAuditToken;
@property (nonatomic) BOOL shouldDisableAlert;
@property (nonatomic) BOOL shouldIssueSandboxExtension;
@property (nonatomic) BOOL shouldTreatAsDeprecated;
@property (nonatomic) BOOL shouldUseADefaultDescriptionString;
@property (retain, nonatomic) NSNumber *tvOS_minimumSDKVersionNumber;
@property (retain, nonatomic) NSString *usageDescriptionKeyName;
@property (nonatomic) BOOL useExternalNotificationOfDenial;
@property (retain, nonatomic) NSSet *validOnPlatformNames;
@property (retain, nonatomic) NSNumber *watchOS_minimumSDKVersionNumber;

@end
