//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, TCCDAccessObject, TCCDIdentity;

@interface TCCDAccessRecord : NSObject {
    TCCDIdentity *_subjectIdentity;
    TCCDAccessObject *_accessObject;
    unsigned long long _authorizationValue;
    unsigned long long _flags;
    NSDate *_lastModifiedDate;
}

- (id)_dateFormatter;
@property (retain) TCCDAccessObject *accessObject;
@property unsigned long long authorizationValue;
- (id)copyWithNewSubject:(id)arg1
                  object:(id)arg2
      authorizationValue:(unsigned long long)arg3
            lastModified:(id)arg4
                   flags:(unsigned long long)arg5;
- (id)description;
- (id)descriptionDictionary;
@property unsigned long long flags;
- (id)initWithSubject:(id)arg1
                object:(id)arg2
    authorizationValue:(unsigned long long)arg3
          lastModified:(id)arg4
                 flags:(unsigned long long)arg5;
@property (retain) NSDate *lastModifiedDate;
@property (retain) TCCDIdentity *subjectIdentity;

@end
