//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSObject, NSString;
@protocol OS_os_log;

@protocol TCCDPolicyOverrideProtected <NSObject>
+ (NSObject<OS_os_log> *)logHandle;
+ (NSString *)useString:(NSString *)arg1
     orReadFromDefaults:(const struct __CFString *)arg2;
- (void)loadAndParse;
@property (retain) NSString *plistFilePath;
@end
