//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class TCCDProcess;

@interface TCCDAttributionChain : NSObject {
    BOOL _accessingProcessSpecified;
    BOOL _accessingProcessIsValid;
    BOOL _responsibleProcessIsValid;
    TCCDProcess *_accessingProcess;
    TCCDProcess *_responsibleProcess;
    TCCDProcess *_requestingProcess;
}

- (id)_prettyGoodGuessForResponsibleProcessesForPrivilegedHelperProcess:
    (id)arg1;
- (id)_processesMeetingRequirements:(id)arg1;
@property (readonly) TCCDProcess *accessingProcess;
@property BOOL accessingProcessIsValid;
@property BOOL accessingProcessSpecified;
- (id)description;
- (id)initWithMessage:(id)arg1;
@property (retain) TCCDProcess *requestingProcess;
@property (readonly) TCCDProcess *responsibleProcess;
@property (readonly) BOOL responsibleProcessIsValid;

@end
