//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSCache, NSFileManager, NSMutableDictionary, NSURL;
@protocol OS_dispatch_queue;

@interface TCCDAdhocSignatureCache : NSObject {
    NSMutableDictionary *_keys;
    NSCache *_signatures;
    unsigned long long _capacity;
    NSURL *_directoryURL;
    NSURL *_keysURL;
    NSFileManager *_fileManager;
    NSObject<OS_dispatch_queue> *_queue;
}

- (void)addSignature:(id)arg1 forStaticCode:(struct __SecCode *)arg2;
- (id)cacheKeyForStaticCode:(struct __SecCode *)arg1;
- (void)createStateHandler;
- (id)getSignatureForStaticCode:(struct __SecCode *)arg1;
- (id)init;
- (id)initWithDirectoryURL:(id)arg1 capacity:(unsigned long long)arg2;
- (void)loadKeysFromDirectory;
- (id)loadSignatureWithUUID:(id)arg1;
- (id)logHandle;
- (void)maintainSize;
- (void)saveKeysToDirectory;
- (void)saveSignature:(id)arg1 withUUID:(id)arg2;
- (id)stateDump;

@end
