//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString, TCCDMasterSyncController, TCCDServer,
    TCCDSyncController;

@interface TCCDPlatform : NSObject {
    NSDictionary *_configurationDictionary;
    NSString *_name;
    TCCDServer *_server;
    TCCDSyncController *_syncController;
    TCCDMasterSyncController *_masterSyncController;
    NSDictionary *_servicesByName;
}

+ (id)allPlatformNames;
+ (id)allTCCEntitlements;
+ (id)currentPlatform;
+ (id)iosFamilyPlatformNames;
+ (id)macOSPlatformNames;
- (void)_configureServices;
- (void)_invalidMethodForPlatform;
- (id)appBundleURLContainingExecutableURL:(id)arg1;
- (id)bundleURLContainingExecutableURL:(id)arg1;
@property (readonly) NSDictionary *configurationDictionary;
- (id)description;
- (long long)evaluatePolicyForPromptingforService:(id)arg1
                                       byIdentity:(id)arg2
                                 attributionChain:(id)arg3;
- (unsigned long long)evalutePolicyForUsageStringAndPromptingForClient:(id)arg1
                                                               service:(id)arg2
                                                     resultUsageString:
                                                         (id *)arg3;
- (void)forwardMessage:(id)arg1
    toUserTCCDFromAttributionChain:(id)arg2
                        forService:(id)arg3
                 andMergeReplyInto:(id)arg4
                    forConnnection:(id)arg5;
- (void)handleCompositionType:(long long)arg1
             forParentService:(id)arg2
                   forRequest:(id)arg3
                    intoReply:(id)arg4;
- (id)homeRelativePathToDatabase;
- (id)initWithName:(id)arg1;
- (BOOL)isNonAppBundleIdentifierValid:(id)arg1;
- (void)loadConfigurationDictionary;
@property (retain) TCCDMasterSyncController *masterSyncController;
@property (readonly) NSString *name;
- (void)notifyUserOfDeniedAccessBy:(id)arg1 forService:(id)arg2;
- (void)prepareForAbort;
- (BOOL)removalOfAppBundleIdentifierRequiresPruning:(id)arg1;
- (void)runBacktraceToolOnTask:(struct __SecTask *)arg1
                       withPID:(int)arg2
                    forService:(id)arg3;
- (void)sendAnalyticsForAction:(long long)arg1
                       service:(id)arg2
               subjectIdentity:(id)arg3
        indirectObjectIdentity:(id)arg4
                     authValue:(unsigned long long)arg5;
- (BOOL)sendMessageAsync:(id)arg1
      toTCCDForTargetUID:(unsigned int)arg2
          withReplyBlock:(CDUnknownBlockType)arg3;
- (id)sendMessageSync:(id)arg1 toTCCDForTargetUID:(unsigned int)arg2;
@property __weak TCCDServer *server;
- (id)serviceByName:(id)arg1;
@property (retain) NSDictionary *servicesByName;
@property (retain) TCCDSyncController *syncController;
- (id)stringForAnalyticsAction:(long long)arg1;
- (void)updateAnalyticsEvent:(id)arg1 fromIdentity:(id)arg2 keyPrefix:(id)arg3;

@end
