//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface TCCDIdentity : NSObject {
    long long _identityType;
    NSString *_identifier;
}

@property (retain) NSString *identifier;
@property long long identityType;
- (id)initWithIdentifier:(id)arg1 type:(long long)arg2;

@end
