//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TCCDAccessIndirectObject.h"

@class NSString;

@interface TCCDAccessFileProviderDomainIndirectObject
    : TCCDAccessIndirectObject {
    NSString *_fileProviderDomainID;
}

- (id)description;
@property (readonly) NSString *fileProviderDomainID;
- (id)initWithFileProviderDomainID:(id)arg1;

@end
