//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSBundle, NSData, NSDictionary, NSNumber, NSString;

@interface TCCDAccessIdentity : NSObject {
    CDUnknownBlockType displayNameBlock;
    unsigned int _sdkVersion;
    unsigned long long _codeSigningErrorFlag;
    struct __SecCode *_derivedStaticCode;
    NSData *_derivedDesignatedRequirementData;
    BOOL _is_wk2_proxy;
    int _client_type;
    int _targetPID;
    int _responsiblePID;
    NSString *_identifier;
    NSNumber *_policy_id;
    NSString *_path;
    NSBundle *_bundle;
    NSDictionary *_plugin;
    struct __SecCode *_guest;
    unsigned long long _codeSigningFlags;
    CDStruct_4c969caf _accessorAuditToken;
    CDStruct_4c969caf _responsibleAuditToken;
}

+ (id)bundleForAppWithBundleIdentifier:(id)arg1;
- (BOOL)_initFromProcessStateAndBinaryPathURL:(id)arg1
                               dynamicCodeRef:(struct __SecCode *)arg2
                 preferMostSpecificIdentifier:(BOOL)arg3;
- (void)_makeDisplayNameBlockForURL:(id)arg1;
@property (readonly) CDStruct_4c969caf accessorAuditToken;
@property (readonly) NSString *attributionPath;
@property (readonly) NSBundle *bundle;
@property (readonly) int client_type;
@property unsigned long long codeSigningFlags;
- (void)dealloc;
- (BOOL)deriveWithAttributionChain:(id)arg1
           platformBinaryFromApple:(char *)arg2
                     signingStatus:(unsigned int *)arg3
                      entitlements:(id *)arg4;
- (id)designatedRequirementData;
- (id)displayName;
- (BOOL)getSDKVersion:(unsigned int *)arg1;
@property (readonly) struct __SecCode *guest;
@property (readonly) NSString *identifier;
- (id)initWithAttributionChain:(id)arg1
    preferMostSpecificIdentifier:(BOOL)arg2;
- (id)initWithBundleIdentifier:(id)arg1 isWK2Proxy:(BOOL)arg2;
- (id)initWithIdentifier:(id)arg1
                    type:(int)arg2
           executableURL:(id)arg3
              SDKVersion:(unsigned int)arg4;
- (id)initWithMessage:(id)arg1;
- (id)initWithPid:(int)arg1
                   accessorToken:(CDStruct_4c969caf)arg2
    preferMostSpecificIdentifier:(BOOL)arg3;
@property (readonly) BOOL is_wk2_proxy;
- (BOOL)matchesCodeRequirementData:(id)arg1;
@property (readonly) NSString *path;
@property (readonly) NSDictionary *plugin;
@property (readonly) NSNumber *policy_id;
@property (readonly) CDStruct_4c969caf responsibleAuditToken;
@property (readonly) int responsiblePID;
- (struct __SecCode *)staticCode;
@property (readonly) int targetPID;

@end
